services:
    oracle_db:
        container_name: oracle_db
        image: gvenzl/oracle-free:23.5
        environment:
            ORACLE_PASSWORD: ictYWwqKEYCA0NP2
        ports:
            - 1521:1521
        volumes:
            - ./server/schema.pls:/usr/src/schema.sql
            - ./server/tables.pls:/usr/src/tables.sql
            - oracle_db_data:/opt/oracle/oradata
        networks:
            - api_network
        restart: always
        healthcheck:
            test: ["CMD", "healthcheck.sh"]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 5s
            start_interval: 5s

    server:
        container_name: server
        image: mcr.microsoft.com/dotnet/sdk:8.0
        working_dir: /usr/src/shakhmat/server
        command: sh -c "dotnet restore && dotnet watch --non-interactive"
        depends_on:
            - oracle_db
        environment:
            DOTNET_WATCH_RESTART_ON_RUDE_EDIT: true
            ASPNETCORE_HTTP_PORTS: 5050
        ports:
            - 5050:5050
        volumes:
            - server_data:/usr/src/shakhmat/server
        networks:
            - api_network
        stdin_open: true
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:5050"]
            interval: 30s
            timeout: 10s
            retries: 5

    server_tests:
        container_name: server_tests
        image: mcr.microsoft.com/dotnet/sdk:8.0
        working_dir: /usr/src/shakhmat/server-tests
        command: sh -c "dotnet restore && trap \"\" INT; while [ true ]; do sleep 1; done;" # Run as a daemon
        depends_on:
            - oracle_db
            - server
        volumes:
            - server_data:/usr/src/shakhmat/server
            - ./server-tests:/usr/src/shakhmat/server-tests
        networks:
            - api_network
        stdin_open: true
        tty: true
    
    client:
        container_name: client
        image: oven/bun:alpine
        working_dir: /usr/src/shakhmat/client
        command: sh -c "bun --bun i && bun --bun run dev"
        depends_on:
            - oracle_db
            - server
        ports:
            - 3000:3000
        volumes:
            - ./client:/usr/src/shakhmat/client
        networks:
            - api_network
        stdin_open: true
        restart: always

networks:
    api_network:
        name: api_network

volumes:
    oracle_db_data:
    server_data:
        driver: local
        driver_opts:
            type: none
            device: ./server
            o: bind
