services:
    oracle_db:
        container_name: oracle_db
        image: gvenzl/oracle-free:23.5
        environment:
            ORACLE_PASSWORD: ictYWwqKEYCA0NP2
        ports:
            - 1521:1521
        volumes:
            - ./server/schema.pls:/usr/src/schema.sql
            - ./server/tables.pls:/usr/src/tables.sql
            - oracle_db_data:/opt/oracle/oradata
        networks:
            - api_network
    server:
        container_name: server
        image: mcr.microsoft.com/dotnet/sdk:8.0
        working_dir: /usr/src/shakhmat/server
        command: sh -c "dotnet restore && dotnet watch --non-interactive"
        depends_on:
            - oracle_db
        environment:
            DOTNET_WATCH_RESTART_ON_RUDE_EDIT: true
            ASPNETCORE_HTTP_PORTS: 5050
        ports:
            - 5050:5050
        volumes:
            - ./server:/usr/src/shakhmat/server
            - /usr/src/shakhmat/server/bin/
            - /usr/src/shakhmat/server/obj/
        networks:
            - api_network
        stdin_open: true
        tty: true
        restart: always
    
    client:
        container_name: client
        image: oven/bun:alpine
        working_dir: /usr/src/shakhmat/client
        command: sh -c "bun --bun i && bun --bun run dev"
        depends_on:
            - oracle_db
            - server
        ports:
            - 3000:3000
        volumes:
            - ./client:/usr/src/shakhmat/client
            # - /usr/src/shakhmat/client/node_modules/
            - /usr/src/shakhmat/client/.next/
        networks:
            - api_network
        stdin_open: true
        tty: true
        restart: always

networks:
    api_network:
        name: api_network

volumes:
    oracle_db_data:
